extends: relaxed
ignore: |
    node_modules/
    node_modules_bak/
    tests/dummy/
rules:
    new-lines: disable
    line-length: disable
    truthy: disable
    indentation:
        spaces: 4
        indent-sequences: true
