import esbuild from 'esbuild';
import process from 'process';
import { builtinModules as builtins } from 'module';

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
    banner: {
        js: '/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\nif you want to view the source, please visit the github repository of this plugin\n*/',
    },
    entryPoints: {
        main: 'main.ts',
        worker: 'src/workers/graph-analysis-worker.ts',
    },
    define: {
        'import.meta.url': 'import.meta.url', // Standard ESM path support
    },
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins,
    ],
    format: 'cjs',
    target: 'es2018',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    outdir: '.',
    treeShaking: true,
    minify: prod, // Minify only in production
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
