export const DASHBOARD_VIEW_TYPE = 'semantic-healer-dashboard';

// --- Internal Obsidian API interfaces ---
export interface ObsidianKeychain {
    get(key: string): Promise<string | null>;
    set(key: string, value: string): Promise<void>;
}

export interface ObsidianSecretStorage {
    getSecret(key: string): Promise<string | null>;
    setSecret(key: string, value: string): Promise<void>;
    deleteSecret?(key: string): Promise<void>;
    listSecrets?(): Promise<string[]>;
}

export interface ObsidianInternalApp {
    secretStorage?: ObsidianSecretStorage;
    keychain?: ObsidianKeychain;
    plugins: {
        enabledPlugins: Set<string>;
        getPlugin(name: string): unknown;
    };
}

// --- Dataview / Datacore API interfaces ---
export interface DataArray<T> {
    array(): T[];
    forEach(cb: (v: T) => void): void;
    filter(cb: (v: T) => boolean): DataArray<T>;
    where(cb: (v: T) => boolean): DataArray<T>;
    length: number;
    [index: number]: T;
}

export interface DataviewApi {
    pages(query?: string): DataArray<DataviewPage>;
    page(path: string): DataviewPage | null;
}

export interface DataviewPage {
    file: {
        path: string;
        name: string;
        basename: string;
        ctime: unknown; // Usually Luxon DateTime
        mtime: unknown;
        size: number;
        tags: string[];
        etags: string[];
        // FIX: Essential Link type for v1 backward compatibility
        link: {
            path: string;
            display?: string;
            subpath?: string;
            embed: boolean;
            type: 'file' | 'header' | 'block';
        };
        frontmatter?: Record<string, unknown>;
    };
    [key: string]: unknown;
}

/**
 * Official Datacore 2026 Interfaces (Sync with blacksmithgu/datacore)
 */
export interface DatacoreApi {
    page<T extends MarkdownPage = MarkdownPage>(path: string): T | undefined;
    query<T = unknown>(query: string): T[];
    tryQuery<T = unknown>(query: string): { successful: true; value: T[] } | { successful: false; error: string };
    resolvePath(path: string, sourcePath?: string): string;
}

export interface MarkdownPage {
    $path: string;
    $typename: string;
    $ctime: unknown; // luxon DateTime
    $mtime: unknown;
    $size: number;
    $tags: string[];
    $links: unknown[]; // Link objects
    $frontmatter?: Record<string, unknown>;
    $infields: Record<string, unknown>;
    [key: string]: unknown; // Custom fields
}

// --- Plugin Core Types ---
/**
 * Types of suggestions generated by the engine.
 * SOTA 2026 Taxonomy:
 * - 'ai': Pure LLM based proximity suggestions.
 * - 'deterministic': Structural/topology based (Bridges, Twins, etc.).
 * - 'quality': Graph metrics based (PageRank/BlackHoles/Cycles).
 * - 'incongruence': Metadata/Property mismatches.
 * - 'infra': External hub gaps (InfraNodus).
 * - 'semantic': Vector embedding matches (Smart Connections).
 * - 'hybrid': Multi-engine consensus suggestions.
 */
export type SuggestionType = 'ai' | 'deterministic' | 'quality' | 'incongruence' | 'infra' | 'semantic' | 'hybrid';

export interface SuggestionMeta {
    property?: string; // Logical type: 'up', 'down', 'next', 'prev', 'same'
    propertyKey?: string; // Actual YAML key: 'parent', 'right', 'procedural-next', etc.
    sourcePath?: string; // Canonical TFile.path for logic
    targetPath?: string; // Canonical TFile.path for logic
    sourceNote?: string; // Basename for display
    targetNote?: string; // Basename for display
    description?: string;
    confidence?: number;
    winner?: string;
    losers?: string[];
    competingValues?: string[];
}

export interface ReasoningResult {
    winner: string | null;
    winnerScore: number;
    winnerWhy: string;
    runnerUp: string | null;
    runnerUpScore: number;
    runnerUpWhy: string;
    rawResponse: string;
}

export interface Suggestion {
    id: string;
    type: SuggestionType;
    category: 'error' | 'suggestion' | 'info';
    link: string;
    source: string;
    timestamp: number; // Re-added for historical tracking
    reasoning?: ReasoningResult;
    meta?: SuggestionMeta;
}

export interface HistoryItem {
    timestamp: number;
    action: string;
    file: string;
    type: string;
}

export interface InfraGap {
    cluster_a?: string;
    cluster_b?: string;
    node1?: string; // v1 alternative field
    node2?: string; // v1 alternative field
    advice?: string | Record<string, unknown>;
    bridging_text?: string; // v1 alternative field
}

export interface SemanticGraphHealerSettings {
    llmApiKey: string; // Added for new security logic
    secondaryLlmApiKey: string; // Added for new security logic
    infraNodusApiKey: string; // Added for network synergy
    llmModelName: string; // Added for model detection logic
    secondaryLlmModelName: string; // Added for tribunal logic
    llmEndpoint: string;
    secondaryLlmEndpoint: string;
    primaryTimeout: number;
    secondaryTimeout: number;
    aiMaxTokens: number;
    aiTemperature: number;
    aiConfidenceThreshold: number;
    enableAiTribunal: boolean;
    llmMaxRetries: number;
    llmRetryableStatuses: number[];
    enableGraphGuardrails: boolean;
    maxNodes: number;
    maxEdges: number;
    aliasCacheTtl: number;
    enableSmartConnections: boolean;
    smartConnectionsLimit: number;
    enableTagHierarchySync: boolean;
    strictDownCheck: boolean;
    scanFolder: string;
    autoFixMundaneLinks: boolean;
    ignoreOrphanNotes: boolean;
    proximityIgnoreList: string[];
    fullyScannedNotes: string[]; // Added for exhausted tracking
    detectedModels: string[]; // Added for scan results
    secondaryDetectedModels: string[]; // Added for scan results
    hierarchies: Array<{
        up: string[];
        down: string[];
        next: string[];
        prev: string[];
        same: string[];
        related: string[];
    }>;
    customTopologyRules: Array<{
        pattern: string;
        property: string;
        maxCount: number;
        severity: 'error' | 'suggestion' | 'info';
    }>;
    pendingSuggestions: Suggestion[];
    history: HistoryItem[];
    lastScanTimestamp: number;
    includeNonMarkdownHubs: boolean;
    impliedSymmetricEdges: boolean;
    impliedTransitiveSiblings: boolean;
    detectTaxonomicSkips: boolean;
    regexExclusionFilter: string;
    enableTemporalAnalysis: boolean;
    enableDynamicOntologyEvolution: boolean;
    mocSaturationThreshold: number;
    aestheticPresetRules: string;
    aiPersonaPreset: string;
    customAiPersonaPrompt: string;
    enableKarpathyFilter: boolean;
    enableInfraNodus: boolean;
    enableDeepGraphAnalysis: boolean;
    enableRealtimeScanning: boolean;
    // Phase 1: Logging & Performance
    logLevel: 'debug' | 'info' | 'warn' | 'error';
    enableFileLogging: boolean;
    logFilePath: string;
    enableHighMemoryMode: boolean;
}

export const DEFAULT_SETTINGS: SemanticGraphHealerSettings = {
    llmApiKey: '',
    secondaryLlmApiKey: '',
    infraNodusApiKey: '',
    llmModelName: '',
    secondaryLlmModelName: '',
    llmEndpoint: 'https://api.openai.com/v1',
    secondaryLlmEndpoint: 'https://api.anthropic.com/v1',
    primaryTimeout: 30,
    secondaryTimeout: 30,
    aiMaxTokens: 1000,
    aiTemperature: 0.7,
    aiConfidenceThreshold: 70,
    enableAiTribunal: false,
    llmMaxRetries: 2,
    llmRetryableStatuses: [429, 408, 503],
    enableGraphGuardrails: true,
    maxNodes: 5000,
    maxEdges: 50000,
    aliasCacheTtl: 300000,
    enableSmartConnections: false,
    smartConnectionsLimit: 10,
    enableTagHierarchySync: true,
    strictDownCheck: true,
    scanFolder: '',
    autoFixMundaneLinks: false,
    ignoreOrphanNotes: false,
    proximityIgnoreList: [],
    fullyScannedNotes: [],
    detectedModels: [],
    secondaryDetectedModels: [],
    hierarchies: [
        {
            up: ['up', 'parent'],
            down: ['down', 'child'],
            next: ['next'],
            prev: ['prev'],
            same: ['same', 'sibling'],
            related: ['related', 'mentions', 'see-also'],
        },
    ],
    customTopologyRules: [],
    pendingSuggestions: [],
    history: [],
    lastScanTimestamp: 0,
    includeNonMarkdownHubs: false,
    impliedSymmetricEdges: true,
    impliedTransitiveSiblings: true,
    detectTaxonomicSkips: true,
    regexExclusionFilter: '',
    enableTemporalAnalysis: true,
    enableDynamicOntologyEvolution: true,
    mocSaturationThreshold: 10,
    aestheticPresetRules: '{}',
    aiPersonaPreset: 'architect',
    customAiPersonaPrompt: '',
    enableKarpathyFilter: true,
    enableInfraNodus: false,
    enableDeepGraphAnalysis: false,
    enableRealtimeScanning: false,
    // Phase 1 Defaults
    logLevel: 'info',
    enableFileLogging: false,
    logFilePath: 'SemanticGraphHealer/logs',
    enableHighMemoryMode: false,
};
