import { HealerLogger } from '../HealerUtils';
import type { HealerAutomationApi, HealerNotifier, Suggestion, TopologicalMetrics, HistoryItem } from '../../types';
import { generateId } from '../HealerUtils';

/**
 * A notification provider that redirects messages to the console instead of the UI.
 * Used during automated headless operations.
 */
class SilentNotifier implements HealerNotifier {
    /**
     * Logs the notification securely to the console via HealerLogger.
     * @param message - The message content to display.
     * @param type - The severity level of the notification.
     */
    show(message: string, type?: 'info' | 'error' | 'warning'): void {
        const logMsg = `[SilentNotifier] ${message}`;
        if (type === 'error') HealerLogger.error(logMsg);
        else if (type === 'warning') HealerLogger.warn(logMsg);
        else HealerLogger.info(logMsg);
    }
}

/**
 * Minimal interface required from SemanticGraphHealer for AutomationApi to work.
 * Avoids direct circular dependency on main.ts.
 */
export interface AutomationPluginContext {
    /** Core execution logic for applying or undoing suggestions. */
    executor: {
        /** Retrieves the current notification provider. */
        getNotifier(): HealerNotifier;
        /** Sets a new notification provider (e.g., SilentNotifier). */
        setNotifier(notifier: HealerNotifier): void;
        /** Executes a single suggestion. */
        execute(suggestion: Suggestion): Promise<boolean>;
        /** Reverts a single history item. */
        undo(historyItem: HistoryItem): Promise<boolean>;
        /** The ID of the current batch being processed, if any. */
        activeBatchId?: string;
    };
    /** Access to the persistent cache of suggestions and history. */
    cache: {
        /** List of pending suggestions generated by the analyzer. */
        suggestions: Suggestion[];
        /** History of applied suggestions for undo support. */
        history: HistoryItem[];
        /** Persists current cache state to disk. */
        save(): void;
        /** Cached topological analysis results. */
        topologicalScores?: {
            pageRank?: Record<string, number>;
            betweenness?: Record<string, number>;
            communities?: Record<string, number>;
        };
    };
    /** Plugin settings snapshot. */
    settings: {
        /** Timestamp of the last successful full graph analysis. */
        lastScanTimestamp: number;
    };
    /** Triggers a full graph analysis workflow. */
    analyzeGraph(silent?: boolean): Promise<void>;
}

/**
 * Provides a high-level API for external tools and automation scripts to interact
 * with the healer's core analysis and execution logic.
 */
export class AutomationApi implements HealerAutomationApi {
    /** Internal notification provider for silent operations. */
    private silentNotifier = new SilentNotifier();

    /**
     * Initializes the Automation API.
     * @param plugin - Context providing executor, cache, and analysis functions.
     */
    constructor(private plugin: AutomationPluginContext) {}

    /**
     * Runs a full graph analysis to generate new suggestions.
     * @param options - Configuration options for the analysis run.
     * @param options.silent - Whether to suppress notifications during the run.
     * @returns A promise that resolves to an array of generated suggestions.
     */
    async runAnalysis(options: { silent: boolean }): Promise<Suggestion[]> {
        const originalNotifier = this.plugin.executor.getNotifier();

        if (options.silent) {
            this.plugin.executor.setNotifier(this.silentNotifier);
        }

        try {
            await this.plugin.analyzeGraph(options.silent);
            return this.getSuggestions();
        } finally {
            if (options.silent) {
                this.plugin.executor.setNotifier(originalNotifier);
            }
        }
    }

    /**
     * Retrieves the current list of pending suggestions.
     * @returns An array of suggestions available for execution.
     */
    getSuggestions(): Suggestion[] {
        // Optimize cloning for large vaults (e.g., shallow clone of properties needed for JSON output only).
        return this.plugin.cache.suggestions.map((s) => ({
            id: s.id,
            type: s.type,
            category: s.category,
            link: s.link,
            source: s.source,
            timestamp: s.timestamp,
            reasoning: s.reasoning ? { ...s.reasoning } : undefined,
            meta: s.meta ? { ...s.meta } : undefined,
        }));
    }

    /**
     * Retrieves the latest calculated topological metrics.
     * @returns The graph metrics or null if analysis hasn't run.
     */
    getMetrics(): TopologicalMetrics | null {
        const cache = this.plugin.cache;
        if (!cache.topologicalScores) return null;

        return {
            pageRank: cache.topologicalScores.pageRank || {},
            betweenness: cache.topologicalScores.betweenness || {},
            communities: cache.topologicalScores.communities || {},
            lastAnalysisTimestamp: this.plugin.settings.lastScanTimestamp,
            graphVersion: 'v1',
        };
    }

    /**
     * Executes a batch of suggestions automatically based on criteria.
     * @param options - Criteria for selecting suggestions to execute.
     * @param options.confidence - Minimum confidence threshold (0-100 or 0-1).
     * @param options.category - Optional category to restrict execution to.
     * @returns A promise resolving to the execution batch results.
     */
    async executeBatch(options: { confidence: number; category?: string }): Promise<{
        success: boolean;
        batchId: string;
        appliedCount: number;
        failedCount: number;
    }> {
        const batchId = generateId('batch');

        // Normalize confidence (0-1 range to 0-100 range)
        const targetConfidence = options.confidence <= 1 ? options.confidence * 100 : options.confidence;

        // Filter suggestions based on confidence and category
        const suggestionsToApply = this.plugin.cache.suggestions.filter((s) => {
            const conf = s.meta?.confidence ?? 0;
            const matchesConfidence = conf >= targetConfidence;
            const matchesCategory = options.category ? s.category === options.category : true;
            return matchesConfidence && matchesCategory;
        });

        if (suggestionsToApply.length === 0) {
            return {
                success: true,
                batchId,
                appliedCount: 0,
                failedCount: 0,
            };
        }

        // Tag all operations in this batch
        this.plugin.executor.activeBatchId = batchId;

        let appliedCount = 0;
        let failedCount = 0;

        try {
            for (const suggestion of suggestionsToApply) {
                const success = await this.plugin.executor.execute(suggestion);
                if (success) {
                    appliedCount++;
                } else {
                    failedCount++;
                }
            }
        } finally {
            this.plugin.executor.activeBatchId = undefined;
        }

        return {
            success: failedCount === 0,
            batchId,
            appliedCount,
            failedCount,
        };
    }

    /**
     * Reverts a previously executed batch of suggestions.
     * @param batchId - The ID of the batch to revert.
     * @returns A promise resolving to the revert batch results.
     */
    async undoBatch(batchId: string): Promise<{
        success: boolean;
        revertedCount: number;
        failedCount: number;
    }> {
        // Find history items belonging to this batch
        const batchItems = this.plugin.cache.history.filter((item) => item.batchId === batchId);

        if (batchItems.length === 0) {
            return {
                success: false,
                revertedCount: 0,
                failedCount: 0,
            };
        }

        let revertedCount = 0;
        let failedCount = 0;

        // Revert in reverse order
        const itemsToUndo = [...batchItems].reverse();

        for (const item of itemsToUndo) {
            const success = await this.plugin.executor.undo(item);
            if (success) {
                revertedCount++;
                const idx = this.plugin.cache.history.indexOf(item);
                if (idx !== -1) {
                    this.plugin.cache.history.splice(idx, 1);
                }
            } else {
                failedCount++;
            }
        }

        // Trigger cache save to persist history changes
        this.plugin.cache.save();

        return {
            success: failedCount === 0,
            revertedCount,
            failedCount,
        };
    }
}
