import esbuild from 'esbuild';
import process from 'process';
import { builtinModules as builtins } from 'module';

const prod = process.argv[2] === 'production';

const commonConfig = {
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins,
    ],
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    minify: prod,
};

// Main build: CJS for Obsidian plugin loader
const mainCtx = await esbuild.context({
    ...commonConfig,
    entryPoints: { main: 'src/main.ts' },
    platform: 'node',
    format: 'cjs',
    target: 'es2018',
    outdir: '.',
    banner: {
        js: '/* GENERATED BY ESBUILD - MAIN PLUGIN */',
    },
});

// Worker build: IIFE for web worker environment
const workerCtx = await esbuild.context({
    ...commonConfig,
    entryPoints: { worker: 'src/core/workers/graph-analysis-worker.ts' },
    platform: 'browser',
    format: 'iife',
    target: 'es2018',
    outdir: '.',
    banner: {
        js: '/* GENERATED BY ESBUILD - GRAPH WORKER */',
    },
});

if (prod) {
    await Promise.all([mainCtx.rebuild(), workerCtx.rebuild()]);
    process.exit(0);
} else {
    await Promise.all([mainCtx.watch(), workerCtx.watch()]);
}
